### ISSUE TITLE
Is qs-init.sh Bash or Shell?

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-quickstart#22]
You mention a "Bash syntax cleanup" in https://github.com/Automattic/vip-go-quickstart/commit/2c041f25d80dc83025f1ddee461376efc5abf2d7, but the [shebang](https://github.com/Automattic/vip-go-quickstart/blob/3ed18252275b3ab0847719497dc7f08a60e690c7/qs-init.sh#L1) is `#!/bin/sh`.

**Comment by ethitter** [comment]
It's shell. That was an inattentive commit message on my part.
