### ISSUE TITLE
Upping a Vagrant is noisy

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-quickstart#25]
Can we suppress the Puppet output unless a `verbose` flag is passed?

**Comment by joshbetz** [comment]
I've thought about this in the past and have decided that I don't think it's a good idea. First, the output doesn't really hurt anything. Not having it could be bad though. If someone's QuickStart breaks, this is the only information we have to go on.

**Comment by ethitter** [comment]
I've thought about the same as I've watched many calls to `vagrant up` scroll by, but as Josh notes, that's the only information we and end users have to act on if something goes wrong. Besides that, Puppet doesn't have an option to suppress notices ([there's an open issue](https://tickets.puppetlabs.com/browse/PUP-1126)), and I'm not sure it's worth the effort to work around that.

**Comment by simonwheatley** [comment]
Fair enough :+1:
