### ISSUE TITLE
We don't need to delete Hello

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-quickstart#26]
We're deleting [Hello Dolly](https://github.com/Automattic/vip-go-quickstart/blob/3ed18252275b3ab0847719497dc7f08a60e690c7/puppet/manifests/wordpress.pp#L55-L58), but we've since [decided not to do this](https://github.com/Automattic/vip-skeleton/issues/1). :smile:

**Comment by joshbetz** [comment]
https://m.youtube.com/watch?v=YQHsXMglC9A

**Comment by simonwheatley** [comment]
:clap:
