### ISSUE TITLE
Virtualbox version in Readme

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-quickstart#41]
The current readme [specifies](https://github.com/Automattic/vip-go-quickstart/blob/2b8f777f46f32b59310611e754cec04a41798c1c/README.md#pre-requisites), but I'm running version `5.0.10 r104061`. 

What version are you on @ethitter?

**Comment by ethitter** [comment]
`Version 5.0.14 r105127`

I'm a poor canary for this, as I tend to be fastidious about updating when VirtualBox prompts.

I'll check with the team as to what version we're all using, but if no one's tested it under 4.3, we should update the readme.

**Comment by ethitter** [comment]
Confirmed with the team that we're running QS under both 4.3 and 5.0, so the README can stay as is for now.
