### ISSUE TITLE
puppet issues

### ISSUE THREAD

**Issue by bobstermyang** [Automattic/vip-go-quickstart#52]
I'm getting a few errors when i run vagrant up, everything is good up until the puppet part....

here's the log: 

==> default: Running provisioner: puppet...
==> default: Running Puppet with default.pp...
==> default: stdin: is not a tty
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Error: Cannot create a location reference without attaching to a virtual host at /tmp/vagrant-puppet/modules-c5ec9f8d8193cd2e0634a4c239aaf63d/nginx/manifests/resource/location.pp:309 on node go-vip.local
==> default: Error: Cannot create a location reference without attaching to a virtual host at /tmp/vagrant-puppet/modules-c5ec9f8d8193cd2e0634a4c239aaf63d/nginx/manifests/resource/location.pp:309 on node go-vip.local
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by bobstermyang** [comment]
Found the solution, totally my fault.....

**Comment by simonwheatley** [comment]
Thanks anyway, @bobstermyang 😄 

Let us know if you have any further issues.
