### ISSUE TITLE
Empty $_GET superglobal

### ISSUE THREAD

**Issue by travisw** [Automattic/vip-go-quickstart#60]
While attempting to debug a site I noticed that my $_GET variable was always empty when there were clearly arguments in the query string `?arg1=123&arg2=456&...`.

Looking at the server block config file for the site
in my case - `/etc/nginx/sites-available/refer.conf`

I noticed the following line
`try_files $uri $uri/ /index.php;`

Adding `?$query_string` to that seems to have fixed it.
`try_files $uri $uri/ /index.php?$query_string;`

I'm not sure if that was intentional or if there's another way to go about fixing it.
Either way I thought I'd bring it to your attention.

**Comment by joshbetz** [comment]
Should be fixed by #51
