### ISSUE TITLE
WP Database not setup properly

### ISSUE THREAD

**Issue by YohannParis** [Automattic/vip-go-quickstart#62]
I just finished to install my first VIP-Go Quickstart, and I get a error message the mess up all my Wordpress configuration.

During the step `3) Starting to provision VM. vagrant up can take some time...`

Wordpress try to setup the database but fail, and a long list of Errors follow:
```shell
==> default: Notice: /Stage[main]/Main/Exec[/usr/bin/wp --allow-root core config --dbname=BIY --dbuser=wordpress --dbpass=wordpress]/returns: ERROR 1045 (28000): Access denied for user 'wordpress'@'localhost' (using password: YES)
```

Once the setup is over after step 4, I go to `http://go-vip.local/` and I am redirected to `http://go-vip.local/wp-admin/setup-config.php` with the error message `wpcom_vip_load_plugin() was called without a first parameter!`

**Comment by joshbetz** [comment]
Howdy! We recommend checking out [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) with [VIP Go mu-plugins](https://github.com/Automattic/vip-go-mu-plugins)
