### ISSUE TITLE
Add support for multiple sites

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-go-quickstart#7]
QS should allow for multiple sites to be run from the same instance.

One way we could do this is to have the site repos in a structure like this;

* puppet
* sites
  * sitename
    * plugins
    * themes
  * site2name
* Vagrantfile

We could perhaps then have `sitename` map to `sitename.local` when setting up hosts. That may require adding a `vvv-hosts` file to the site skeleton.

At the moment, puppet installs WP once, so we'll need to change that to loop through each site dir and create `/var/www/sitename/`

**Comment by simonwheatley** [comment]
Alternative approach suggested in this PR: #9

**Comment by simonwheatley** [comment]
We'll stick with one site at a time for now
