### ISSUE TITLE
Use different IP address and hostname from WordPress.com VIP Quickstart

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-quickstart#8]
Currently we use the same IP address and hostname as VIP Quickstart, so it is confusing to know which Quickstart you're accessing. We should not do this. :)

**Comment by simonwheatley** [comment]
A further step to dynamically assigned hostnames and IP addresses would allow us to run multiple VIP Go Quickstarts in one host machine at the same time.

**Comment by ethitter** [comment]
#9 addressed the hostname and IP address updates.

For reasons discussed in #13 (speed, primarily), we aren't supporting dynamic hostnames at this time.
